export { Header } from './header/Header';
export { Trending } from './trending/Trending';
export { Leaderboard } from './leaderboard/Leaderboard';
export { Footer } from './footer/Footer';
export { FeaturedCollections } from './featured-collections/FeaturedCollections';
export { Explore } from './explore/Explore';
export { DownloadCard } from './download-card/DownloadCard';
export { CTA } from './cta/CTA';
export { CreateNFT } from './create-nft/CreateNFT';